version: "3.9"
services:
    app:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: always                               
        ports:                                         
            - "8080"                                     
        container_name: ${APP_NAME}_app                
        environment:                                    
            VIRTUAL_HOST: ${HOST_DOMAIN}
            VIRTUAL_PORT: 8080 # New default ASP.NET port -> https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port
            LETSENCRYPT_HOST: ${HOST_DOMAIN}           
            LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}    
        volumes:
            - app-mydb:/app/App_Data  

    app-migration:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION} 
        restart: "no"                                  
        container_name: ${APP_NAME}_app_migration       
        profiles:                                      
            - migration                                
        command: --AppTasks=migrate                     
        volumes:
            - app-mydb:/app/App_Data  


    db-init:
        image: ghcr.io/${IMAGE_REPO}:${RELEASE_VERSION}
        restart: "no"
        user: root
        profiles:
            - db-init
        working_dir: "/app"
        entrypoint: ""
        command: /bin/bash -c "chown 1654:1654 /app/App_Data"
        volumes:
            - app-mydb:/app/App_Data

networks:
  default:
    external: true                                     
    name: nginx                                        

volumes:
    app-mydb:                                          
